### ISSUE TITLE
Slow unzip performance via DMS

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/girder_wt_data_manager#39]
Working with the new "Seal Tale" example, I'm seeing slower than expected performance extracting zip archives via DMS.  This Tale extracts data from 30 zip files (using R!) that are all < 1M. The tests below were all run using cached data on staging.wholetale.org (Chameleon):

1. Register dataset doi:10.24431/rw1k118 
2. Compose environment mounting this data
3. Unzip one archive to a tmp directory (this one is ~735K)
```
$ cd data
$ mkdir /tmp/test
$ time unzip -d /tmp/test EB2004_5972_04L0016.zip
real	0m7.012s
...
``` 

4. Copy the zip and unzip in tmp directly
```
$ rm /tmp/test/*
$ time cp  EB2004_5972_04L0016.zip /tmp
real	0m2.449s
...
$ time unzip -d /tmp/test /tmp/EB2004_5972_04L0016.zip 
real	0m0.073s
...
```
5. Compare to  git clone of repo containing all 30 files data
```
$ time git clone https://github.com/jmlondon/crwexampleakbs
...
real	0m10.121s
```
Unzipping all 30 files directly in /tmp takes ~2 seconds.

For the full dataset, unzipping all 30 files in parallel from DMS took over 1 minute (sequentially took ~13 minutes). Copying the files to tmp in parallel then unzipping took ~25 seconds (4 minutes sequential).  In comparison, cloning the repo from Github to tmp and unzipping directly took ~15 seconds.

A short term solution for this example would be to modify the researcher's code to copy the files before extracting.

**Comment by Xarthisius** [comment]
When you write WebDav you really mean data DMS right?

**Comment by craig-willis** [comment]
I should've meant DMS, but had it mixed up.  I think I've covered my tracks.

**Comment by Xarthisius** [comment]
A couple of things:
1. I guess it's expected. Zipfiles are a "special" beast. During extract, low level i/o routines are only requesting a certain range of bytes from a file. DMS is able to fulfill those requests and also read only a certain portion of a file. This works nicely, when you grab one file from 5Gb zip archive, but not so much when you extract everything and to make matter works individual files have sizes less than 100 bytes... In this case network latency and python fuse overhead dominates the operation (I haven't thoroughly checked that, it's just my gut feeling).
2. It shows how slow our deployment is overall:
```
$ time unzip -o -d /tmp/full -q '*.zip'

30 archives were successfully processed.

real    3m59.984s
user    0m0.953s
sys     0m0.086s
```
Above is seq unzip run locally.

For reference testing:

```
$ cat /tmp/ala.py
import zipfile
import sys
import io
import tempfile
import time
import subprocess

fname = '/tmp/foo/Satellite Telemetry Dataset (Raw): Juvenile Bearded and Spotted Seals, 2004-2006, Kotzebue, Alaska/EB2004_5972_04L0016.zip'
fname = '/tmp/foo/Satellite Telemetry Dataset (Raw): Juvenile Bearded and Spotted Seals, 2004-2006, Kotzebue, Alaska/EB2006_5940_SN10465.zip'

print('Read once to make sure it is cached in DMS')
start = time.time()
with open(fname, 'rb') as fp:
    fp.read()
print("Elapsed time: {}s".format(time.time() - start))

print('Read and unzip from memory')
start = time.time()
with open(fname, 'rb') as fp:
    data = io.BytesIO(fp.read())

z = zipfile.ZipFile(data)
z.extractall(tempfile.mkdtemp())
print("Elapsed time: {}s".format(time.time() - start))

print('Unzip from disk')
start = time.time()
z = zipfile.ZipFile(fname)
z.extractall(tempfile.mkdtemp())
print("Elapsed time: {}s".format(time.time() - start))

print('Unzip using "unzip -d"')
start = time.time()
directory = tempfile.mkdtemp()
subprocess.call("unzip -d {} '{}'".format(directory, fname), shell=True)
print("Elapsed time: {}s".format(time.time() - start))
```

```
$ python /tmp/ala.py
Read once to make sure it is cached in DMS
Elapsed time: 1.26375412940979s
Read and unzip from memory
Elapsed time: 1.2334232330322266s
Unzip from disk
Elapsed time: 3.424302577972412s
Unzip using "unzip -d"
Elapsed time: 3.3834002017974854s
```

**Comment by hategan** [comment]
I'll look at it. AFAIK zip files have a file table at the end of the file and there is a pointer to it in the beginning of the file, so maybe this access pattern (read a few bytes from the start, read some bytes at the end, read stuff in the middle) is problematic here. In principle, the performance should not be significantly worse than wget ... | unzip.

**Comment by hategan** [comment]
Ok, so I think my assertion that the jumping around in the zip file has much to do with it isn't quite right.

The FUSE driver downloads the file sequentially. However, as an optimization, if a read() is requested, it does not wait for the full file to be downloaded in order to service the read(); only the relevant chunk of data. In other words, it can be no worse than waiting for the full file to be downloaded on the FUSE machine. However, since zip files do have the file table at the end, this effectively means that unzipping cannot proceed until the whole file is downloaded.

Typically, with a random access file and a typical filesystem, unzip ends up parallelizing I/O and CPU ops for various reasons (it seems to be using two threads, which can intersperse the ops, OS readahead, etc.), and ideally, in our case, I/O would also mean the grider -> local traffic. Except it doesn't because of the above.

In theory, girder supports downloading pieces of a file. So it may be possible to have some smart mechanism to optimize such scenarios (i.e., start the download of the full file, but also fill in pieces based on read() requests as needed).

**Comment by Xarthisius** [comment]
@hategan BTW, I think there's some flaw in the cache logic that may (or may not) be related. Look at my example above. Subsequent operations should be faster since file is already downloaded right?

It's also apparent here:
```
$ girderfs -c wt_dms --api-url https://girder.local.wholetale.org/api/v1 --api-key NVQq5DrVik89tMMIS71iWktA0UG4HAyV0DEKC1i2 /tmp/foo 5ca6432af9f18900016b834e 
$ time unzip -qq -o -d aaaa /tmp/foo/EB2006_5946_05L0098.zip 

real    0m8.779s
user    0m0.030s
sys     0m0.003s
$ echo "second execution of the same command"
second execution of the same command
$ time unzip -qq -o -d aaaa /tmp/foo/EB2006_5946_05L0098.zip 

real    0m6.581s
user    0m0.027s
sys     0m0.009s
$ fusermount -u /tmp/foo
$ girderfs -c wt_dms --api-url https://girder.local.wholetale.org/api/v1 --api-key NVQq5DrVik89tMMIS71iWktA0UG4HAyV0DEKC1i2 /tmp/foo 5ca6432af9f18900016b834e 
xarth@shakuras /tmp $ time unzip -qq -o -d aaaa /tmp/foo/EB2006_5946_05L0098.zip 

real    0m0.308s
user    0m0.032s
sys     0m0.007s
$ time unzip -qq -o -d aaaa /tmp/foo/EB2006_5946_05L0098.zip 

real    0m0.167s
user    0m0.032s
sys     0m0.003s
$ time unzip -qq -o -d aaaa /tmp/foo/EB2006_5946_05L0098.zip 

real    0m0.178s
user    0m0.030s
sys     0m0.006s
```
looks like during the initial session *every* operation re-downloads the file

**Comment by hategan** [comment]
The girderfs fix should be relevant here. In my tests it changes the unzip time from 6s to 2s even on the first attempt (when nothing is cached locally or in DMS).
